baseURL = 'https://rust-vulkan-guide.com'
defaultContentLanguage = 'en'
title = 'Rust Vulkan Guide'
theme = 'hugo-theme-relearn'
pluralizeListTitles = false
enableGitInfo = true

[params]
	themeVariant = "zen-dark"
	collapsibleMenu = true
	disableLandingPageButton = true
	showVisitedLinks = true
	ordersectionsby = 'date'

[caches]
	[caches.images]
		dir = ':cacheDir/images'

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			[markup.goldmark.parser.attribute]
				block = true

[languages]
	[languages.en]
		contentDir = 'content/en'
		languageName = 'English'
		weight = 1
		[[languages.en.menu.shortcuts]]
			name = "<i class='fab fa-fw fa-github'></i> Tutorial code"
			url = "https://github.com/FacelessTiger/rust-vulkan-guide/tree/tutorial-code"

	[languages.es]
		contentDir = 'content/es'
		languageName = 'Español'
		title = 'Spanish Rust Vulkan Guide'
		weight = 2
		[[languages.es.menu.shortcuts]]
			name = "<i class='fab fa-fw fa-github'></i> Código del tutorial"
			url = "https://github.com/FacelessTiger/rust-vulkan-guide/tree/tutorial-code"