baseURL = 'https://rust-vulkan-guide.com'
languageCode = 'en-us'
title = 'Rust Vulkan Guide'
theme = 'hugo-theme-relearn'
pluralizeListTitles = false
enableGitInfo = true

[params]
	themeVariant = "zen-dark"
	collapsibleMenu = true
	disableLandingPageButton = true
	showVisitedLinks = true
	ordersectionsby = 'date'

[caches]
	[caches.images]
		dir = ':cacheDir/images'

[markup]
	[markup.goldmark]
		[markup.goldmark.parser]
			[markup.goldmark.parser.attribute]
				block = true

[[menu.shortcuts]]
	name = "<i class='fab fa-fw fa-github'></i> Tutorial Code"
	url = "https://github.com/FacelessTiger/rust-vulkan-guide/tree/tutorial-code"